name: 🐞 Bug report
description: Report a bug or an issue.
title: 'bug: '
labels: ['Bug report']
body:
  - type: markdown
    attributes:
      value: |
        # Bug report

        Before creating a new bug report, please keep the following in mind:

        - **Do not submit a duplicate bug report**: Search for existing bug reports [here](https://github.com/wchill/revanced-patches/issues?q=label%3A%22Bug+report%22).
        - **Review the contribution guidelines**: Make sure your bug report adheres to it. You can find the guidelines [here](https://github.com/wchill/revanced-patches/blob/main/CONTRIBUTING.md).
        - **Check the troubleshooting guide**: A solution to your issue might be found in the [FAQ](https://github.com/ReVanced/revanced-documentation/blob/main/docs/revanced-resources/questions.md) or the [troubleshooting guide](https://github.com/ReVanced/revanced-documentation/blob/main/docs/revanced-resources/troubleshooting.md).
        - **Do not use the issue page for support**: If you need help or have questions, check out other platforms on [revanced.app](https://revanced.app).
  - type: textarea
    attributes:
      label: Bug description
      description: |
        - Describe your bug in detail
        - Add steps to reproduce the bug if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
        - List used patches if applicable
    validations:
        required: true
  - type: textarea
    attributes:
      label: Error logs
      description: Exceptions can be captured by running `logcat | grep AndroidRuntime` in a shell.
      render: shell
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution to the bug.
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your bug report will be closed if you don't follow the checklist below.
      options:
        - label: I have checked all open and closed bug reports and this is not a duplicate.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
